plugins:
  - rubocop-rails
  - rubocop-rspec

## Layout

Layout/LineLength:
  Max: 144


## Style

# Do not report errors on missing documentation.
Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19
  SupportedStyles:
    - ruby19
    - hash_rockets
  EnforcedShorthandSyntax: either

Style/NumericLiterals:
  Enabled: true
  MinDigits: 5

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false


## Metrics

Metrics/AbcSize:
  Enabled: false

# Do not complain about blocks that are too long.
Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false


## Rspec

# We decide how many lines.
RSpec/ExampleLength:
  Enabled: false

# We decide how many expectations.
RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Description: Checks for nested example groups.
  Enabled: true
  Max: 5

## Rails

Rails/I18nLocaleTexts:
  Enabled: false

Rails/SaveBang:
  Enabled: true

## Miscellaneous

AllCops:
  TargetRubyVersion: 3.3.0
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "config/**/*"
    - "bin/**/*"
    - "db/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "test/rails_helper.rb"
    - "test/test_helper.rb"
    - "vendor/**/*"
    - "config.ru"
    - "Rakefile"
    - "lib/tasks/auto_annotate_models.rake"
